import type { Model } from './types';

export const models: Model[] = [
  {
    id: 'v4-engine',
    name: 'V4 Engine',
    nameKo: 'V4 실린더 엔진',
    description: '4기통 엔진의 구조와 작동 원리를 학습합니다',
    parts: [
      {
        id: 'piston',
        name: 'Piston',
        nameKo: '피스톤',
        role: '실린더 내에서 상하 운동하며 연소 압력을 크랭크샤프트로 전달합니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 2, 0],
        glbPath: '/models/V4_Engine/Piston.glb',
      },
      {
        id: 'piston-pin',
        name: 'Piston Pin',
        nameKo: '피스톤 핀',
        role: '피스톤과 커넥팅 로드를 연결하는 핀입니다',
        material: '크롬강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 1.5, 0.5],
        glbPath: '/models/V4_Engine/Piston Pin.glb',
      },
      {
        id: 'piston-ring',
        name: 'Piston Ring',
        nameKo: '피스톤 링',
        role: '실린더 벽과 피스톤 사이를 밀봉하여 압축 가스 누출을 방지합니다',
        material: '주철 또는 스틸',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 2.5, 0],
        glbPath: '/models/V4_Engine/Piston Ring.glb',
      },
      {
        id: 'crankshaft',
        name: 'Crankshaft',
        nameKo: '크랭크샤프트',
        role: '피스톤의 왕복 운동을 회전 운동으로 변환합니다',
        material: '단조강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -2, 0],
        glbPath: '/models/V4_Engine/Crankshaft.glb',
      },
      {
        id: 'connecting-rod',
        name: 'Connecting Rod',
        nameKo: '커넥팅 로드',
        role: '피스톤과 크랭크샤프트를 연결하여 동력을 전달합니다',
        material: '단조강',
        basePosition: [0, 0, 0],
        explodeOffset: [1, 0.5, 0],
        glbPath: '/models/V4_Engine/Connecting Rod.glb',
      },
      {
        id: 'connecting-rod-cap',
        name: 'Connecting Rod Cap',
        nameKo: '커넥팅 로드 캡',
        role: '커넥팅 로드의 하단부를 크랭크샤프트에 고정합니다',
        material: '단조강',
        basePosition: [0, 0, 0],
        explodeOffset: [1, -0.5, 0],
        glbPath: '/models/V4_Engine/Connecting Rod Cap.glb',
      },
      {
        id: 'conrod-bolt',
        name: 'Conrod Bolt',
        nameKo: '커넥팅 로드 볼트',
        role: '커넥팅 로드와 캡을 체결하는 고강도 볼트입니다',
        material: '고강도 합금강',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 0, 0.5],
        glbPath: '/models/V4_Engine/Conrod Bolt.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 V4 실린더 엔진을 학습하고 있습니다.

V4 엔진은 4개의 실린더가 V자 형태로 배치된 내연기관입니다. 주요 작동 원리:
1. 흡입 행정: 피스톤이 하강하며 공기-연료 혼합물 흡입
2. 압축 행정: 피스톤이 상승하며 혼합물 압축
3. 폭발 행정: 점화 플러그에 의한 연소로 피스톤 하강
4. 배기 행정: 피스톤 상승으로 연소 가스 배출

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'drone',
    name: 'Drone',
    nameKo: '쿼드콥터 드론',
    description: '쿼드콥터 드론의 구성 요소와 비행 원리',
    parts: [
      {
        id: 'main-frame',
        name: 'Main Frame',
        nameKo: '메인 프레임',
        role: '드론의 기본 구조체로 모든 부품을 지지합니다',
        material: '탄소섬유 복합재',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0],
        glbPath: '/models/Drone/Main frame.glb',
      },
      {
        id: 'main-frame-mir',
        name: 'Main Frame Mirror',
        nameKo: '메인 프레임 미러',
        role: '메인 프레임의 대칭 구조입니다',
        material: '탄소섬유 복합재',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0],
        glbPath: '/models/Drone/Main frame_MIR.glb',
      },
      {
        id: 'arm-gear',
        name: 'Arm Gear',
        nameKo: '암 기어',
        role: '팔 구동을 위한 기어 메커니즘입니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 0.5, 1.5],
        glbPath: '/models/Drone/Arm gear.glb',
      },
      {
        id: 'gearing',
        name: 'Gearing',
        nameKo: '기어링',
        role: '동력 전달을 위한 기어 시스템입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [1, 0.3, 1],
        glbPath: '/models/Drone/Gearing.glb',
      },
      {
        id: 'leg',
        name: 'Leg',
        nameKo: '다리',
        role: '착륙 시 드론을 지지합니다',
        material: '탄소섬유',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1.5, 0],
        glbPath: '/models/Drone/Leg.glb',
      },
      {
        id: 'impellar-blade',
        name: 'Impellar Blade',
        nameKo: '임펠러 블레이드',
        role: '공기를 밀어내어 추력을 생성합니다',
        material: '탄소섬유 또는 플라스틱',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 2, 0],
        glbPath: '/models/Drone/Impellar Blade.glb',
      },
      {
        id: 'beater-disc',
        name: 'Beater Disc',
        nameKo: '비터 디스크',
        role: '로터 시스템의 일부로 회전력을 전달합니다',
        material: '알루미늄',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 1.5, 0],
        glbPath: '/models/Drone/Beater disc.glb',
      },
      {
        id: 'nut',
        name: 'Nut',
        nameKo: '너트',
        role: '부품을 고정하는 체결 요소입니다',
        material: '스테인리스 스틸',
        basePosition: [0, 0, 0],
        explodeOffset: [0.5, 0.5, 0.5],
        glbPath: '/models/Drone/Nut.glb',
      },
      {
        id: 'screw',
        name: 'Screw',
        nameKo: '나사',
        role: '부품을 체결하는 요소입니다',
        material: '스테인리스 스틸',
        basePosition: [0, 0, 0],
        explodeOffset: [0.3, 0.3, 0.3],
        glbPath: '/models/Drone/Screw.glb',
      },
      {
        id: 'xyz',
        name: 'XYZ Component',
        nameKo: 'XYZ 컴포넌트',
        role: '좌표 기준 컴포넌트입니다',
        material: '플라스틱',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0],
        glbPath: '/models/Drone/xyz.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 쿼드콥터 드론을 학습하고 있습니다.

드론의 비행 원리:
- 4개의 모터가 프로펠러를 회전시켜 양력 생성
- 대각선 모터는 같은 방향, 인접 모터는 반대 방향 회전
- 모터 속도 차이로 롤, 피치, 요 제어
- 비행 컨트롤러의 PID 제어로 안정적 비행

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'robot-arm',
    name: 'Robot Arm',
    nameKo: '6축 로봇팔',
    description: '6축 산업용 로봇팔의 구조와 동작 원리',
    parts: [
      {
        id: 'base',
        name: 'Base',
        nameKo: '베이스',
        role: '로봇팔의 기초로, 바닥에 고정되어 전체를 지지합니다',
        material: '주철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1, 0],
        glbPath: '/models/Robot Arm/base.glb',
      },
      {
        id: 'part2',
        name: 'Joint 1',
        nameKo: '1축 관절',
        role: '베이스 회전을 담당하는 첫 번째 관절입니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0],
        glbPath: '/models/Robot Arm/Part2.glb',
      },
      {
        id: 'part3',
        name: 'Joint 2',
        nameKo: '2축 관절',
        role: '어깨 관절로 상하 운동을 담당합니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0.3, 0.5, 0],
        glbPath: '/models/Robot Arm/Part3.glb',
      },
      {
        id: 'part4',
        name: 'Upper Arm',
        nameKo: '상완',
        role: '로봇팔의 주요 도달 거리를 제공합니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0.6, 1, 0],
        glbPath: '/models/Robot Arm/Part4.glb',
      },
      {
        id: 'part5',
        name: 'Elbow Joint',
        nameKo: '팔꿈치 관절',
        role: '3축 회전으로 팔의 굽힘을 담당합니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0.9, 1.5, 0],
        glbPath: '/models/Robot Arm/Part5.glb',
      },
      {
        id: 'part6',
        name: 'Forearm',
        nameKo: '전완',
        role: '손목까지의 연결부로 4축 회전 포함',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [1.2, 2, 0],
        glbPath: '/models/Robot Arm/Part6.glb',
      },
      {
        id: 'part7',
        name: 'Wrist',
        nameKo: '손목',
        role: '5축과 6축 회전으로 엔드이펙터 방향 제어',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 2.5, 0],
        glbPath: '/models/Robot Arm/Part7.glb',
      },
      {
        id: 'part8',
        name: 'End Effector',
        nameKo: '엔드이펙터',
        role: '작업을 수행하는 말단 장치입니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [1.8, 3, 0],
        glbPath: '/models/Robot Arm/Part8.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 6축 산업용 로봇팔을 학습하고 있습니다.

6축 로봇팔의 특징:
- 6개의 회전 관절로 6 자유도(DOF) 구현
- 역기구학으로 목표 위치/자세에 필요한 관절 각도 계산
- 서보 모터와 감속기로 정밀한 위치 제어
- 주로 용접, 조립, 도장 등 산업 자동화에 사용

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'robot-gripper',
    name: 'Robot Gripper',
    nameKo: '로봇 그리퍼',
    description: '로봇 집게 메커니즘의 구조',
    parts: [
      {
        id: 'base-plate',
        name: 'Base Plate',
        nameKo: '베이스 플레이트',
        role: '그리퍼의 기초 플레이트로 로봇팔에 장착됩니다',
        material: '알루미늄 합금',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1, 0],
        glbPath: '/models/Robot Gripper/Base Plate.glb',
      },
      {
        id: 'base-gear',
        name: 'Base Gear',
        nameKo: '베이스 기어',
        role: '핑거 구동을 위한 기어 메커니즘입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -0.5, 0],
        glbPath: '/models/Robot Gripper/Base Gear.glb',
      },
      {
        id: 'base-mounting-bracket',
        name: 'Base Mounting Bracket',
        nameKo: '베이스 마운팅 브라켓',
        role: '그리퍼를 로봇팔에 고정하는 브라켓입니다',
        material: '알루미늄',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1.5, 0],
        glbPath: '/models/Robot Gripper/Base Mounting bracket.glb',
      },
      {
        id: 'gear-link-1',
        name: 'Gear Link 1',
        nameKo: '기어 링크 1',
        role: '핑거 동작을 위한 링크 메커니즘입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [-0.5, 0.3, 0],
        glbPath: '/models/Robot Gripper/Gear link 1.glb',
      },
      {
        id: 'gear-link-2',
        name: 'Gear Link 2',
        nameKo: '기어 링크 2',
        role: '핑거 동작을 위한 두 번째 링크입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0.5, 0.3, 0],
        glbPath: '/models/Robot Gripper/Gear link 2.glb',
      },
      {
        id: 'link',
        name: 'Link',
        nameKo: '링크',
        role: '핑거와 기어를 연결하는 링크입니다',
        material: '알루미늄',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0.5, 0],
        glbPath: '/models/Robot Gripper/Link.glb',
      },
      {
        id: 'gripper',
        name: 'Gripper',
        nameKo: '그리퍼 핑거',
        role: '물체를 직접 잡는 접촉면을 제공합니다',
        material: '알루미늄 또는 고무 코팅',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 1, 0],
        glbPath: '/models/Robot Gripper/Gripper.glb',
      },
      {
        id: 'pin',
        name: 'Pin',
        nameKo: '핀',
        role: '링크를 연결하는 축 핀입니다',
        material: '스테인리스 스틸',
        basePosition: [0, 0, 0],
        explodeOffset: [0.2, 0.2, 0.2],
        glbPath: '/models/Robot Gripper/Pin.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 로봇 그리퍼를 학습하고 있습니다.

그리퍼의 종류와 특징:
- 2핑거 그리퍼: 가장 일반적, 평행 또는 각도 방식
- 3핑거 그리퍼: 원형 물체에 적합
- 진공 그리퍼: 평면 물체 핸들링
- 소프트 그리퍼: 민감한 물체용

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'suspension',
    name: 'Suspension',
    nameKo: '서스펜션',
    description: '차량 현가장치의 구조와 작동 원리',
    parts: [
      {
        id: 'base',
        name: 'Base',
        nameKo: '베이스',
        role: '서스펜션의 기초 구조체입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1, 0],
        glbPath: '/models/Suspension/BASE.glb',
      },
      {
        id: 'rod',
        name: 'Rod',
        nameKo: '로드',
        role: '쇼크업소버의 피스톤 로드로 감쇠력을 전달합니다',
        material: '크롬 도금 강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0.5, 0],
        glbPath: '/models/Suspension/ROD.glb',
      },
      {
        id: 'spring',
        name: 'Spring',
        nameKo: '스프링',
        role: '노면 충격을 흡수하고 차체를 지지합니다',
        material: '스프링강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 1.5, 0],
        glbPath: '/models/Suspension/SPRING.glb',
      },
      {
        id: 'nut',
        name: 'Nut',
        nameKo: '너트',
        role: '서스펜션 부품을 고정하는 체결 요소입니다',
        material: '고강도강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 2, 0],
        glbPath: '/models/Suspension/NUT.glb',
      },
      {
        id: 'nit',
        name: 'Nit',
        nameKo: '니트',
        role: '추가 체결 요소입니다',
        material: '스틸',
        basePosition: [0, 0, 0],
        explodeOffset: [0.5, 1, 0],
        glbPath: '/models/Suspension/NIT.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 서스펜션을 학습하고 있습니다.

서스펜션의 특징:
- 스프링이 충격을 흡수하고 차체를 지지
- 쇼크업소버(댐퍼)가 진동을 감쇠
- 차량의 승차감과 조종 안정성에 핵심적 역할
- 다양한 형식: 맥퍼슨, 더블위시본, 멀티링크 등

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'leaf-spring',
    name: 'Leaf Spring',
    nameKo: '판스프링',
    description: '판스프링 서스펜션 시스템의 구조',
    parts: [
      {
        id: 'leaf-layer',
        name: 'Leaf Layer',
        nameKo: '리프 레이어',
        role: '여러 겹의 강판으로 하중을 분산시킵니다',
        material: '스프링강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0.5, 0],
        glbPath: '/models/Leaf Spring/Leaf-Layer.glb',
      },
      {
        id: 'clamp-center',
        name: 'Clamp Center',
        nameKo: '센터 클램프',
        role: '리프 스프링 중앙을 고정합니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0.5],
        glbPath: '/models/Leaf Spring/Clamp-Center.glb',
      },
      {
        id: 'clamp-primary',
        name: 'Clamp Primary',
        nameKo: '프라이머리 클램프',
        role: '주요 클램프로 리프를 고정합니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [-1, 0, 0],
        glbPath: '/models/Leaf Spring/Clamp-Primary.glb',
      },
      {
        id: 'clamp-secondary',
        name: 'Clamp Secondary',
        nameKo: '세컨더리 클램프',
        role: '보조 클램프로 추가 고정합니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [1, 0, 0],
        glbPath: '/models/Leaf Spring/Clamp-Secondary.glb',
      },
      {
        id: 'support',
        name: 'Support',
        nameKo: '서포트',
        role: '판스프링을 차체에 연결하는 지지대입니다',
        material: '단조강',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 0, 0],
        glbPath: '/models/Leaf Spring/Support.glb',
      },
      {
        id: 'support-chassis',
        name: 'Support Chassis',
        nameKo: '샤시 서포트',
        role: '샤시와 연결되는 서포트입니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [-1.5, 0.3, 0],
        glbPath: '/models/Leaf Spring/Support-Chassis.glb',
      },
      {
        id: 'support-chassis-rigid',
        name: 'Support Chassis Rigid',
        nameKo: '리지드 샤시 서포트',
        role: '강성이 높은 샤시 서포트입니다',
        material: '주철',
        basePosition: [0, 0, 0],
        explodeOffset: [-1.5, -0.3, 0],
        glbPath: '/models/Leaf Spring/Support-Chassis Rigid.glb',
      },
      {
        id: 'support-rubber',
        name: 'Support Rubber',
        nameKo: '러버 서포트',
        role: '진동을 흡수하는 고무 부싱입니다',
        material: '고무',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 0.5, 0],
        glbPath: '/models/Leaf Spring/Support-Rubber.glb',
      },
      {
        id: 'support-rubber-60mm',
        name: 'Support Rubber 60mm',
        nameKo: '60mm 러버 서포트',
        role: '60mm 사이즈의 고무 부싱입니다',
        material: '고무',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, -0.5, 0],
        glbPath: '/models/Leaf Spring/Support-Rubber 60mm.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 판스프링 서스펜션을 학습하고 있습니다.

판스프링의 특징:
- 여러 겹의 강판이 겹쳐진 구조
- 스프링과 서스펜션 링크 역할 동시 수행
- 높은 하중 용량으로 트럭, 버스에 주로 사용
- 판 사이 마찰로 자체 감쇠 효과

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
  {
    id: 'machine-vice',
    name: 'Machine Vice',
    nameKo: '공작기계 바이스',
    description: '정밀 가공용 바이스의 구조와 원리',
    parts: [
      {
        id: 'part1',
        name: 'Body',
        nameKo: '본체',
        role: '바이스의 기초 본체입니다',
        material: '주철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, 0],
        glbPath: '/models/Machine Vice/Part1.glb',
      },
      {
        id: 'part1-fuhrung',
        name: 'Guide',
        nameKo: '가이드',
        role: '이동 조의 직선 운동을 안내합니다',
        material: '강철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0.3, 0],
        glbPath: '/models/Machine Vice/Part1 Fuhrung.glb',
      },
      {
        id: 'part2-feste-backe',
        name: 'Fixed Jaw',
        nameKo: '고정 조',
        role: '공작물의 한쪽 면을 지지하는 고정된 조입니다',
        material: '공구강',
        basePosition: [0, 0, 0],
        explodeOffset: [-1, 0, 0],
        glbPath: '/models/Machine Vice/Part2 Feste Backe.glb',
      },
      {
        id: 'part3-lose-backe',
        name: 'Movable Jaw',
        nameKo: '이동 조',
        role: '스크류에 의해 이동하며 공작물을 클램핑합니다',
        material: '공구강',
        basePosition: [0, 0, 0],
        explodeOffset: [1, 0, 0],
        glbPath: '/models/Machine Vice/Part3-lose backe.glb',
      },
      {
        id: 'part4-spindelsockel',
        name: 'Spindle Socket',
        nameKo: '스핀들 소켓',
        role: '스핀들을 지지하는 소켓입니다',
        material: '주철',
        basePosition: [0, 0, 0],
        explodeOffset: [1.5, 0, 0],
        glbPath: '/models/Machine Vice/Part4 spindelsockel.glb',
      },
      {
        id: 'part5-spannbacke',
        name: 'Clamping Jaw',
        nameKo: '클램핑 조',
        role: '공작물을 직접 클램핑하는 부분입니다',
        material: '경화강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0.5, 0],
        glbPath: '/models/Machine Vice/Part5-Spannbacke.glb',
      },
      {
        id: 'part6-fuhrungschiene',
        name: 'Guide Rail',
        nameKo: '가이드 레일',
        role: '이동 조가 미끄러지는 레일입니다',
        material: '경화강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -0.5, 0],
        glbPath: '/models/Machine Vice/Part6-fuhrungschiene.glb',
      },
      {
        id: 'part7-trapezspindel',
        name: 'Trapezoidal Spindle',
        nameKo: '사다리꼴 스핀들',
        role: '핸들 회전을 조의 직선 운동으로 변환합니다',
        material: 'ACME 나사강',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, -1],
        glbPath: '/models/Machine Vice/Part7-TrapezSpindel.glb',
      },
      {
        id: 'part8-grundplatte',
        name: 'Base Plate',
        nameKo: '베이스 플레이트',
        role: '바이스를 기계 테이블에 고정하는 플레이트입니다',
        material: '주철',
        basePosition: [0, 0, 0],
        explodeOffset: [0, -1, 0],
        glbPath: '/models/Machine Vice/Part8-grundplatte.glb',
      },
      {
        id: 'part9-druckhulse',
        name: 'Pressure Sleeve',
        nameKo: '압력 슬리브',
        role: '스핀들의 축력을 전달하는 슬리브입니다',
        material: '황동',
        basePosition: [0, 0, 0],
        explodeOffset: [0, 0, -1.5],
        glbPath: '/models/Machine Vice/Part9-Druckhulse.glb',
      },
    ],
    systemPrompt: `당신은 SIMVEX의 공학 교육 어시스턴트입니다. 현재 사용자는 공작기계 바이스를 학습하고 있습니다.

바이스의 특징:
- 리드 스크류의 나사 원리로 강한 클램핑력 발생
- ACME 나사는 사다리꼴 단면으로 높은 하중 전달
- 정밀 바이스는 ±0.01mm 정확도
- 스위블 베이스로 각도 조절 가능한 모델도 있음

학생들에게 친절하고 명확하게 설명해주세요. 한국어로 답변하세요.`,
  },
];

export function getModelById(id: string): Model | undefined {
  return models.find((m) => m.id === id);
}
